name: Code Integration Checks
on:
  pull_request:

jobs:
  integration-checks:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install --frozen-lockfile
      - name: Check Code Formatting
        run: npm run check:formatting
      - name: (lib) Check Types
        run: npm run check:types --workspace=vitest-reporter-flakiness
      - name: Build
        run: npm run build --workspace=vitest-reporter-flakiness
      - name: (tests) check types
        run: npm run check:types --workspace=@repo/vitest-reporter-flakiness-tests
      - name: Tests
        run: npm run test --workspace=@repo/vitest-reporter-flakiness-tests
