name: Example Workflow

on:
  pull_request:

jobs:
  integration-checks:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install --frozen-lockfile
      - name: Build library
        run: npm run build --workspace=vitest-reporter-flakiness
      - name: Run tests to generate a flakiness report
        run: npm run test --workspace=@repo/app-with-ci
      - name: Report flaky tests
        run: |
          if [ -f "examples/app-with-ci/reports/flaky-tests.json" ]; then
            # TODO: this is where you would want to send a notification or create an issue based on the flakiness report.
            echo "Artifacts: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
      - name: Upload flaky test report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flaky-tests-report
          path: examples/app-with-ci/reports/flaky-tests.json
          if-no-files-found: ignore
