name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Check Code Formatting
        run: npm run check:formatting
      - name: Check Types
        run: npm run check:types --workspace=vitest-reporter-flakiness
      - name: Build
        run: npm run build --workspace=vitest-reporter-flakiness
      - name: Copy README into the workspace
        run: |
          cp README.md packages/vitest-reporter-flakiness/
          cp LICENSE packages/vitest-reporter-flakiness/
      # TODO remove ODE_AUTH_TOKEN="" when this is fixed: https://github.com/actions/setup-node/issues/1440
      - name: Get package version
        id: pkg
        run: echo "version=$(node -p 'require(\"./packages/vitest-reporter-flakiness/package.json\").version')" >> $GITHUB_OUTPUT
      - name: Publish to NPM
        run: |
          TAG=latest
          if [[ "${{ steps.pkg.outputs.version }}" == *-* ]]; then
            TAG=next
          fi
          echo "Publishing with tag: $TAG"
          NODE_AUTH_TOKEN="" npm publish --workspace=vitest-reporter-flakiness --tag $TAG
